# Generated by Django 5.2.6 on 2025-09-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatFeedback',
        ),
    ]
