# Generated by Django 5.2.6 on 2025-09-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_weather_alerts',
            field=models.BooleanField(default=True, help_text='Receive weather alert notifications'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firebase_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True),
        ),
    ]
