# Generated by Django 5.2.6 on 2025-09-22 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_id', models.CharField(help_text='Unique ID from NWS API', max_length=500, unique=True)),
                ('event', models.CharField(help_text='Type of weather event', max_length=200)),
                ('headline', models.CharField(help_text='Alert headline', max_length=500)),
                ('description', models.TextField(help_text='Detailed alert description')),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Extreme', 'Extreme')], help_text='Alert severity level', max_length=20)),
                ('area', models.CharField(help_text='Geographic area description', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_id'], name='alerts_aler_source__9cce1d_idx'), models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'), models.Index(fields=['created_at'], name='alerts_aler_created_8af5ce_idx')],
            },
        ),
    ]
